name: gc_wizard
description: GC Wizard
version: 2.1.0+135

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  archive: ^3.1.2
  auto_size_text: ^3.0.0
  base32: ^2.0.0
  cached_network_image: ^3.1.0
  diacritic: ^0.1.1
  file_picker: ^4.1.0
  file_picker_writable: ^2.0.1
  encrypt: ^5.0.0
  exif: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.13.1
  flutter_map_marker_popup: ^1.0.1
  flutter_map_tappable_polyline: ^3.0.0
  fluttertoast: ^8.0.8
  http: ^0.13.4
  image: ^3.1.1
  intl: ^0.17.0
  location: ^4.3.0
  mask_text_input_formatter: ^2.0.0
  math_expressions: ^2.3.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  photo_view: ^0.13.0
  pointycastle: ^3.3.3
  prefs: ^3.3.0
  provider: ^6.0.1
  qr: ^3.0.0
  r_scan: ^0.1.6+1
  scrollable_positioned_list: ^0.2.3
  touchable: ^1.0.0
  universal_html: ^2.0.4
  uuid: ^3.0.4
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/logo/
    - assets/icons/coords/
    - assets/icons/science_and_technology/
    - assets/quadgrams/
    - assets/tokens/
    - assets/searchstrings/
    - assets/symbol_tables/
    - assets/symbol_tables/adlam/
    - assets/symbol_tables/albhed/
    - assets/symbol_tables/alchemy/
    - assets/symbol_tables/alchemy_alphabet/
    - assets/symbol_tables/alphabetum_arabum/
    - assets/symbol_tables/alphabetum_egiptiorum/
    - assets/symbol_tables/alphabetum_gothicum/
    - assets/symbol_tables/angerthas_cirth/
    - assets/symbol_tables/antiker/
    - assets/symbol_tables/arabic_indian_numerals/
    - assets/symbol_tables/arcadian/
    - assets/symbol_tables/ath/
    - assets/symbol_tables/atlantean/
    - assets/symbol_tables/aurebesh/
    - assets/symbol_tables/australian_sign_language/
    - assets/symbol_tables/babylonian_numerals/
    - assets/symbol_tables/ballet/
    - assets/symbol_tables/barbier/
    - assets/symbol_tables/barcode39/
    - assets/symbol_tables/baudot_1888/
    - assets/symbol_tables/baudot_54123/
    - assets/symbol_tables/birds_on_a_wire/
    - assets/symbol_tables/blox/
    - assets/symbol_tables/brahmi_numerals/
    - assets/symbol_tables/braille_de/
    - assets/symbol_tables/braille_en/
    - assets/symbol_tables/braille_eu/
    - assets/symbol_tables/braille_fr/
    - assets/symbol_tables/british_sign_language/
    - assets/symbol_tables/chain_of_death_direction/
    - assets/symbol_tables/chain_of_death_pairs/
    - assets/symbol_tables/chappe_1794/
    - assets/symbol_tables/chappe_1809/
    - assets/symbol_tables/chappe_v1/
    - assets/symbol_tables/cherokee/
    - assets/symbol_tables/chinese_numerals/
    - assets/symbol_tables/christmas/
    - assets/symbol_tables/cirth_erebor/
    - assets/symbol_tables/cistercian/
    - assets/symbol_tables/color_add/
    - assets/symbol_tables/color_code/
    - assets/symbol_tables/color_honey/
    - assets/symbol_tables/color_tokki/
    - assets/symbol_tables/cookewheatstone_1/
    - assets/symbol_tables/cookewheatstone_2/
    - assets/symbol_tables/cookewheatstone_5/
    - assets/symbol_tables/country_flags/
    - assets/symbol_tables/covenant/
    - assets/symbol_tables/cyrillic/
    - assets/symbol_tables/cyrillic_numbers/
    - assets/symbol_tables/daedric/
    - assets/symbol_tables/dagger/
    - assets/symbol_tables/dancing_men/
    - assets/symbol_tables/deafblind/
    - assets/symbol_tables/devanagari_numerals/
    - assets/symbol_tables/dni/
    - assets/symbol_tables/dni_colors/
    - assets/symbol_tables/dni_numbers/
    - assets/symbol_tables/doop_speak/
    - assets/symbol_tables/dorabella/
    - assets/symbol_tables/doremi/
    - assets/symbol_tables/dragon_language/
    - assets/symbol_tables/dragon_runes/
    - assets/symbol_tables/eastern_arabic_indian_numerals/
    - assets/symbol_tables/egyptian_numerals/
    - assets/symbol_tables/elia/
    - assets/symbol_tables/enochian/
    - assets/symbol_tables/eurythmy/
    - assets/symbol_tables/face_it/
    - assets/symbol_tables/fakoo/
    - assets/symbol_tables/fez/
    - assets/symbol_tables/finger/
    - assets/symbol_tables/finger_numbers/
    - assets/symbol_tables/flags/
    - assets/symbol_tables/flags_german_kriegsmarine/
    - assets/symbol_tables/flags_nato/
    - assets/symbol_tables/flags_rn_howe/
    - assets/symbol_tables/flags_rn_marryat/
    - assets/symbol_tables/flags_rn_popham/
    - assets/symbol_tables/fonic/
    - assets/symbol_tables/four_triangles/
    - assets/symbol_tables/freemason/
    - assets/symbol_tables/freemason_v2/
    - assets/symbol_tables/futurama/
    - assets/symbol_tables/futurama_2/
    - assets/symbol_tables/gallifreyan/
    - assets/symbol_tables/gargish/
    - assets/symbol_tables/gc_attributes_ids/
    - assets/symbol_tables/gc_attributes_meaning/
    - assets/symbol_tables/gernreich/
    - assets/symbol_tables/gerudo/
    - assets/symbol_tables/glagolitic/
    - assets/symbol_tables/gnommish/
    - assets/symbol_tables/greek_numerals/
    - assets/symbol_tables/hangul_korean/
    - assets/symbol_tables/hangul_sino_korean/
    - assets/symbol_tables/hanja/
    - assets/symbol_tables/hazard/
    - assets/symbol_tables/hebrew/
    - assets/symbol_tables/hebrew_v2/
    - assets/symbol_tables/hexahue/
    - assets/symbol_tables/hieratic_numerals/
    - assets/symbol_tables/hieroglyphs/
    - assets/symbol_tables/hobbit_runes/
    - assets/symbol_tables/hvd/
    - assets/symbol_tables/hylian_64/
    - assets/symbol_tables/hylian_albw_botw/
    - assets/symbol_tables/hylian_skyward_sword/
    - assets/symbol_tables/hylian_symbols/
    - assets/symbol_tables/hylian_twilight_princess_gcn/
    - assets/symbol_tables/hylian_twilight_princess_wii/
    - assets/symbol_tables/hylian_wind_waker/
    - assets/symbol_tables/hymmnos/
    - assets/symbol_tables/icecodes/
    - assets/symbol_tables/iching/
    - assets/symbol_tables/illuminati_v1/
    - assets/symbol_tables/illuminati_v2/
    - assets/symbol_tables/intergalactic/
    - assets/symbol_tables/iokharic/
    - assets/symbol_tables/ita1_1926/
    - assets/symbol_tables/ita1_1929/
    - assets/symbol_tables/ita2_1929/
    - assets/symbol_tables/ita2_1931/
    - assets/symbol_tables/japanese_numerals/
    - assets/symbol_tables/kabouter_abc/
    - assets/symbol_tables/kabouter_abc_1947/
    - assets/symbol_tables/kartrak/
    - assets/symbol_tables/kharoshthi/
    - assets/symbol_tables/klingon/
    - assets/symbol_tables/klingon_klinzhai/
    - assets/symbol_tables/krempel/
    - assets/symbol_tables/krypton/
    - assets/symbol_tables/lorm/
    - assets/symbol_tables/magicode/
    - assets/symbol_tables/mandalorian/
    - assets/symbol_tables/marain/
    - assets/symbol_tables/marain_v2/
    - assets/symbol_tables/matoran/
    - assets/symbol_tables/maya_calendar_haab_codices/
    - assets/symbol_tables/maya_calendar_haab_inscripts/
    - assets/symbol_tables/maya_calendar_longcount/
    - assets/symbol_tables/maya_calendar_tzolkin_codices/
    - assets/symbol_tables/maya_calendar_tzolkin_inscripts/
    - assets/symbol_tables/maya_numerals/
    - assets/symbol_tables/maze/
    - assets/symbol_tables/minimoys/
    - assets/symbol_tables/moon/
    - assets/symbol_tables/murray/
    - assets/symbol_tables/murray_v2_fischer_corrected/
    - assets/symbol_tables/murray_v3_navy_1796/
    - assets/symbol_tables/murray_v4_roucoux/
    - assets/symbol_tables/murraybaudot/
    - assets/symbol_tables/musica/
    - assets/symbol_tables/nazcaan/
    - assets/symbol_tables/new_zealand_sign_language/
    - assets/symbol_tables/niessen/
    - assets/symbol_tables/notes_doremi/
    - assets/symbol_tables/notes_notevalues/
    - assets/symbol_tables/notes_names_altoclef/
    - assets/symbol_tables/notes_names_bassclef/
    - assets/symbol_tables/notes_names_trebleclef/
    - assets/symbol_tables/notes_restvalues/
    - assets/symbol_tables/nyctography/
    - assets/symbol_tables/ogham/
    - assets/symbol_tables/optical_fiber_fotag/
    - assets/symbol_tables/optical_fiber_iec60304/
    - assets/symbol_tables/optical_fiber_swisscom/
    - assets/symbol_tables/phoenician/
    - assets/symbol_tables/pipeline/
    - assets/symbol_tables/pipeline_din2403/
    - assets/symbol_tables/pixel/
    - assets/symbol_tables/planet/
    - assets/symbol_tables/planets/
    - assets/symbol_tables/pokemon_unown/
    - assets/symbol_tables/postcode_01247/
    - assets/symbol_tables/postcode_8421/
    - assets/symbol_tables/postnet/
    - assets/symbol_tables/predator/
    - assets/symbol_tables/prosyl/
    - assets/symbol_tables/prussian_colors_artillery/
    - assets/symbol_tables/prussian_colors_infantery/
    - assets/symbol_tables/puzzle/
    - assets/symbol_tables/quadoo/
    - assets/symbol_tables/reality/
    - assets/symbol_tables/red_herring/
    - assets/symbol_tables/resistor/
    - assets/symbol_tables/rhesus_a/
    - assets/symbol_tables/rhesus_b/
    - assets/symbol_tables/rhesus_c1/
    - assets/symbol_tables/rhesus_c2/
    - assets/symbol_tables/rm4scc/
    - assets/symbol_tables/romulan/
    - assets/symbol_tables/runes/
    - assets/symbol_tables/sanluca/
    - assets/symbol_tables/sarati/
    - assets/symbol_tables/semaphore/
    - assets/symbol_tables/shadoks/
    - assets/symbol_tables/sheikah/
    - assets/symbol_tables/shoes/
    - assets/symbol_tables/sign/
    - assets/symbol_tables/siemens/
    - assets/symbol_tables/skullz/
    - assets/symbol_tables/slash_and_pipe/
    - assets/symbol_tables/solmisation/
    - assets/symbol_tables/space_invaders/
    - assets/symbol_tables/spintype/
    - assets/symbol_tables/stippelcode/
    - assets/symbol_tables/suetterlin/
    - assets/symbol_tables/sunuz/
    - assets/symbol_tables/surf/
    - assets/symbol_tables/tae/
    - assets/symbol_tables/tamil_numerals/
    - assets/symbol_tables/telegraph_prussia/
    - assets/symbol_tables/templers/
    - assets/symbol_tables/tenctonese/
    - assets/symbol_tables/tengwar_beleriand/
    - assets/symbol_tables/tengwar_classic/
    - assets/symbol_tables/tengwar_general/
    - assets/symbol_tables/terzi/
    - assets/symbol_tables/theban/
    - assets/symbol_tables/three_squares/
    - assets/symbol_tables/tines/
    - assets/symbol_tables/tomtom/
    - assets/symbol_tables/trafficsigns_germany/
    - assets/symbol_tables/ulog/
    - assets/symbol_tables/unitology/
    - assets/symbol_tables/utopian/
    - assets/symbol_tables/visitor_1984/
    - assets/symbol_tables/visitor_2009/
    - assets/symbol_tables/vulcanian/
    - assets/symbol_tables/wakandan/
    - assets/symbol_tables/weather_a/
    - assets/symbol_tables/weather_c/
    - assets/symbol_tables/weather_cl/
    - assets/symbol_tables/weather_cm/
    - assets/symbol_tables/weather_ch/
    - assets/symbol_tables/weather_n/
    - assets/symbol_tables/weather_w/
    - assets/symbol_tables/weather_ww/
    - assets/symbol_tables/webdings/
    - assets/symbol_tables/westernunion/
    - assets/symbol_tables/windforce_beaufort/
    - assets/symbol_tables/windforce_knots/
    - assets/symbol_tables/window/
    - assets/symbol_tables/wingdings/
    - assets/symbol_tables/wingdings2/
    - assets/symbol_tables/wingdings3/
    - assets/symbol_tables/yan_koryani/
    - assets/symbol_tables/yinyang/
    - assets/symbol_tables/zamonian/
    - assets/symbol_tables/zentradi/
    - assets/symbol_tables/zodiac_signs/
    - assets/symbol_tables/zodiac_signs_latin/
    - assets/symbol_tables/zodiac_z340/
    - assets/symbol_tables/zodiac_z408/

flutter_icons:
  image_path: "assets/logo/circle_border_1024_gold.png"
  android: true
  ios: true