name: gc_wizard
description: GC Wizard
version: 3.0.0+5
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  archive: ^3.3.7
  audioplayers: ^5.0.0
  auto_size_text: ^3.0.0
  base32: ^2.1.3
  cached_network_image: ^3.2.2
  code_text_field: ^1.1.0
  collection: ^1.17.1
  diacritic: ^0.1.1
  encrypt: ^5.0.0
  exif: ^3.1.4
  file_picker: ^5.3.3
  file_picker_writable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: ^5.2.0
  flutter_map_tappable_polyline: ^5.0.0
  fluttertoast: ^8.2.2
  highlight: ^0.7.0
  http: ^1.1.0
  http_parser: ^4.0.2
  image: ^4.0.16
  intl: ^0.18.0
  latlong2: ^0.9.0
  location: ^5.0.1
  mask_text_input_formatter: ^2.5.0
  math_expressions: ^2.4.0
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.1.0
  photo_view: ^0.14.0
  pointycastle: ^3.7.3
  prefs: ^4.1.0+3
  provider: ^6.0.4
  qr: ^3.0.1
  r_scan:
    git:
      url: https://github.com/S-Man42/r_scan.git
  scrollable_positioned_list: ^0.3.7
  shared_preferences: ^2.1.1
  touchable: ^1.0.2
  tuple: ^2.0.1
  universal_html: ^2.2.3
  unrar_file: ^1.1.0
  uuid: ^3.0.6
  url_launcher: ^6.1.11
  utility: ^1.0.3
  week_of_year: ^2.0.0
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: 0.12.0
  flutter_lints: ^2.0.1

flutter:
  fonts:
    - family: Courier
      fonts:
        - asset: lib/application/_common/assets/fonts/Courier_Prime/CourierPrime-Bold.ttf
        - asset: lib/application/_common/assets/fonts/Courier_Prime/CourierPrime-BoldItalic.ttf
        - asset: lib/application/_common/assets/fonts/Courier_Prime/CourierPrime-Italic.ttf
        - asset: lib/application/_common/assets/fonts/Courier_Prime/CourierPrime-Regular.ttf
    - family: Roboto
      fonts:
        - asset: lib/application/_common/assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: lib/application/_common/assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: lib/application/_common/assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: lib/application/_common/assets/fonts/Roboto/Roboto-Regular.ttf
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/tokens/
    - lib/application/_common/assets/img/
    - lib/application/i18n/assets/
    - lib/application/searchstrings/assets/
    - lib/tools/coords/_common/assets/icons/
    - lib/tools/crypto_and_encodings/general_codebreakers/substitution_breaker/assets/quadgrams/
    - lib/tools/science_and_technology/astronomy/iau_constellation/assets/
    - lib/tools/science_and_technology/segment_display/7_segment_display/assets/
    - lib/tools/science_and_technology/segment_display/14_segment_display/assets/
    - lib/tools/science_and_technology/segment_display/16_segment_display/assets/
    - lib/tools/symbol_tables/_common/assets/adlam/
    - lib/tools/symbol_tables/_common/assets/albhed/
    - lib/tools/symbol_tables/_common/assets/alchemy/
    - lib/tools/symbol_tables/_common/assets/alchemy_alphabet/
    - lib/tools/symbol_tables/_common/assets/alien_mushrooms/
    - lib/tools/symbol_tables/_common/assets/alphabetum_arabum/
    - lib/tools/symbol_tables/_common/assets/alphabetum_egiptiorum/
    - lib/tools/symbol_tables/_common/assets/alphabetum_gothicum/
    - lib/tools/symbol_tables/_common/assets/angerthas_cirth/
    - lib/tools/symbol_tables/_common/assets/antiker/
    - lib/tools/symbol_tables/_common/assets/arabic_indian_numerals/
    - lib/tools/symbol_tables/_common/assets/arcadian/
    - lib/tools/symbol_tables/_common/assets/ath/
    - lib/tools/symbol_tables/_common/assets/atlantean/
    - lib/tools/symbol_tables/_common/assets/aurebesh/
    - lib/tools/symbol_tables/_common/assets/australian_sign_language/
    - lib/tools/symbol_tables/_common/assets/babylonian_numerals/
    - lib/tools/symbol_tables/_common/assets/ballet/
    - lib/tools/symbol_tables/_common/assets/barbier/
    - lib/tools/symbol_tables/_common/assets/barcode39/
    - lib/tools/symbol_tables/_common/assets/baudot_1888/
    - lib/tools/symbol_tables/_common/assets/baudot_54123/
    - lib/tools/symbol_tables/_common/assets/birds_on_a_wire/
    - lib/tools/symbol_tables/_common/assets/blox/
    - lib/tools/symbol_tables/_common/assets/blue_monday/
    - lib/tools/symbol_tables/_common/assets/brahmi_numerals/
    - lib/tools/symbol_tables/_common/assets/braille_de/
    - lib/tools/symbol_tables/_common/assets/braille_en/
    - lib/tools/symbol_tables/_common/assets/braille_eu/
    - lib/tools/symbol_tables/_common/assets/braille_fr/
    - lib/tools/symbol_tables/_common/assets/british_sign_language/
    - lib/tools/symbol_tables/_common/assets/chain_of_death_direction/
    - lib/tools/symbol_tables/_common/assets/chain_of_death_pairs/
    - lib/tools/symbol_tables/_common/assets/chappe_1794/
    - lib/tools/symbol_tables/_common/assets/chappe_1809/
    - lib/tools/symbol_tables/_common/assets/chappe_v1/
    - lib/tools/symbol_tables/_common/assets/cherokee/
    - lib/tools/symbol_tables/_common/assets/chinese_numerals/
    - lib/tools/symbol_tables/_common/assets/christmas/
    - lib/tools/symbol_tables/_common/assets/cirth_erebor/
    - lib/tools/symbol_tables/_common/assets/cistercian/
    - lib/tools/symbol_tables/_common/assets/color_add/
    - lib/tools/symbol_tables/_common/assets/color_code/
    - lib/tools/symbol_tables/_common/assets/color_honey/
    - lib/tools/symbol_tables/_common/assets/color_tokki/
    - lib/tools/symbol_tables/_common/assets/cookewheatstone_1/
    - lib/tools/symbol_tables/_common/assets/cookewheatstone_2/
    - lib/tools/symbol_tables/_common/assets/cookewheatstone_5/
    - lib/tools/symbol_tables/_common/assets/country_flags/
    - lib/tools/symbol_tables/_common/assets/covenant/
    - lib/tools/symbol_tables/_common/assets/crystal/
    - lib/tools/symbol_tables/_common/assets/cyrillic/
    - lib/tools/symbol_tables/_common/assets/cyrillic_numbers/
    - lib/tools/symbol_tables/_common/assets/daedric/
    - lib/tools/symbol_tables/_common/assets/dagger/
    - lib/tools/symbol_tables/_common/assets/dancing_men/
    - lib/tools/symbol_tables/_common/assets/deafblind/
    - lib/tools/symbol_tables/_common/assets/devanagari_numerals/
    - lib/tools/symbol_tables/_common/assets/dinotopia/
    - lib/tools/symbol_tables/_common/assets/dni/
    - lib/tools/symbol_tables/_common/assets/dni_colors/
    - lib/tools/symbol_tables/_common/assets/dni_numbers/
    - lib/tools/symbol_tables/_common/assets/doop_speak/
    - lib/tools/symbol_tables/_common/assets/dorabella/
    - lib/tools/symbol_tables/_common/assets/doremi/
    - lib/tools/symbol_tables/_common/assets/dragon_language/
    - lib/tools/symbol_tables/_common/assets/dragon_runes/
    - lib/tools/symbol_tables/_common/assets/eastern_arabic_indian_numerals/
    - lib/tools/symbol_tables/_common/assets/egyptian_numerals/
    - lib/tools/symbol_tables/_common/assets/elia/
    - lib/tools/symbol_tables/_common/assets/enochian/
    - lib/tools/symbol_tables/_common/assets/eurythmy/
    - lib/tools/symbol_tables/_common/assets/face_it/
    - lib/tools/symbol_tables/_common/assets/fakoo/
    - lib/tools/symbol_tables/_common/assets/fez/
    - lib/tools/symbol_tables/_common/assets/finger/
    - lib/tools/symbol_tables/_common/assets/finger_numbers/
    - lib/tools/symbol_tables/_common/assets/flags/
    - lib/tools/symbol_tables/_common/assets/flags_german_kriegsmarine/
    - lib/tools/symbol_tables/_common/assets/flags_nato/
    - lib/tools/symbol_tables/_common/assets/flags_rn_howe/
    - lib/tools/symbol_tables/_common/assets/flags_rn_marryat/
    - lib/tools/symbol_tables/_common/assets/flags_rn_popham/
    - lib/tools/symbol_tables/_common/assets/fonic/
    - lib/tools/symbol_tables/_common/assets/four_triangles/
    - lib/tools/symbol_tables/_common/assets/freemason/
    - lib/tools/symbol_tables/_common/assets/freemason_v2/
    - lib/tools/symbol_tables/_common/assets/futurama/
    - lib/tools/symbol_tables/_common/assets/futurama_2/
    - lib/tools/symbol_tables/_common/assets/gallifreyan/
    - lib/tools/symbol_tables/_common/assets/gargish/
    - lib/tools/symbol_tables/_common/assets/gc_attributes_ids/
    - lib/tools/symbol_tables/_common/assets/gc_attributes_meaning/
    - lib/tools/symbol_tables/_common/assets/gernreich/
    - lib/tools/symbol_tables/_common/assets/gerudo/
    - lib/tools/symbol_tables/_common/assets/glagolitic/
    - lib/tools/symbol_tables/_common/assets/gnommish/
    - lib/tools/symbol_tables/_common/assets/greek_numerals/
    - lib/tools/symbol_tables/_common/assets/hangul_korean/
    - lib/tools/symbol_tables/_common/assets/hangul_sino_korean/
    - lib/tools/symbol_tables/_common/assets/hanja/
    - lib/tools/symbol_tables/_common/assets/hazard/
    - lib/tools/symbol_tables/_common/assets/hebrew/
    - lib/tools/symbol_tables/_common/assets/hebrew_v2/
    - lib/tools/symbol_tables/_common/assets/hexahue/
    - lib/tools/symbol_tables/_common/assets/hieratic_numerals/
    - lib/tools/symbol_tables/_common/assets/hieroglyphs/
    - lib/tools/symbol_tables/_common/assets/hieroglyphs_v2/
    - lib/tools/symbol_tables/_common/assets/hobbit_runes/
    - lib/tools/symbol_tables/_common/assets/hvd/
    - lib/tools/symbol_tables/_common/assets/hylian_64/
    - lib/tools/symbol_tables/_common/assets/hylian_albw_botw/
    - lib/tools/symbol_tables/_common/assets/hylian_skyward_sword/
    - lib/tools/symbol_tables/_common/assets/hylian_symbols/
    - lib/tools/symbol_tables/_common/assets/hylian_twilight_princess_gcn/
    - lib/tools/symbol_tables/_common/assets/hylian_twilight_princess_wii/
    - lib/tools/symbol_tables/_common/assets/hylian_wind_waker/
    - lib/tools/symbol_tables/_common/assets/hymmnos/
    - lib/tools/symbol_tables/_common/assets/icecodes/
    - lib/tools/symbol_tables/_common/assets/iching/
    - lib/tools/symbol_tables/_common/assets/illuminati_v1/
    - lib/tools/symbol_tables/_common/assets/illuminati_v2/
    - lib/tools/symbol_tables/_common/assets/intergalactic/
    - lib/tools/symbol_tables/_common/assets/interlac/
    - lib/tools/symbol_tables/_common/assets/iokharic/
    - lib/tools/symbol_tables/_common/assets/ita1_1926/
    - lib/tools/symbol_tables/_common/assets/ita1_1929/
    - lib/tools/symbol_tables/_common/assets/ita2_1929/
    - lib/tools/symbol_tables/_common/assets/ita2_1931/
    - lib/tools/symbol_tables/_common/assets/japanese_numerals/
    - lib/tools/symbol_tables/_common/assets/kabouter_abc/
    - lib/tools/symbol_tables/_common/assets/kabouter_abc_1947/
    - lib/tools/symbol_tables/_common/assets/kartrak/
    - lib/tools/symbol_tables/_common/assets/kaktovik/
    - lib/tools/symbol_tables/_common/assets/kharoshthi/
    - lib/tools/symbol_tables/_common/assets/klingon/
    - lib/tools/symbol_tables/_common/assets/klingon_klinzhai/
    - lib/tools/symbol_tables/_common/assets/krempel/
    - lib/tools/symbol_tables/_common/assets/krypton/
    - lib/tools/symbol_tables/_common/assets/la_buse/
    - lib/tools/symbol_tables/_common/assets/linear_b/
    - lib/tools/symbol_tables/_common/assets/lorm/
    - lib/tools/symbol_tables/_common/assets/magicode/
    - lib/tools/symbol_tables/_common/assets/mandalorian/
    - lib/tools/symbol_tables/_common/assets/marain/
    - lib/tools/symbol_tables/_common/assets/marain_v2/
    - lib/tools/symbol_tables/_common/assets/matoran/
    - lib/tools/symbol_tables/_common/assets/maya_calendar_haab_codices/
    - lib/tools/symbol_tables/_common/assets/maya_calendar_haab_inscripts/
    - lib/tools/symbol_tables/_common/assets/maya_calendar_longcount/
    - lib/tools/symbol_tables/_common/assets/maya_calendar_tzolkin_codices/
    - lib/tools/symbol_tables/_common/assets/maya_calendar_tzolkin_inscripts/
    - lib/tools/symbol_tables/_common/assets/maya_numerals/
    - lib/tools/symbol_tables/_common/assets/maze/
    - lib/tools/symbol_tables/_common/assets/minimoys/
    - lib/tools/symbol_tables/_common/assets/moon/
    - lib/tools/symbol_tables/_common/assets/moon_phases/
    - lib/tools/symbol_tables/_common/assets/morse/
    - lib/tools/symbol_tables/_common/assets/murray/
    - lib/tools/symbol_tables/_common/assets/murray_v2_fischer_corrected/
    - lib/tools/symbol_tables/_common/assets/murray_v3_navy_1796/
    - lib/tools/symbol_tables/_common/assets/murray_v4_roucoux/
    - lib/tools/symbol_tables/_common/assets/murraybaudot/
    - lib/tools/symbol_tables/_common/assets/musica/
    - lib/tools/symbol_tables/_common/assets/nazcaan/
    - lib/tools/symbol_tables/_common/assets/new_zealand_sign_language/
    - lib/tools/symbol_tables/_common/assets/niessen/
    - lib/tools/symbol_tables/_common/assets/ninjargon/
    - lib/tools/symbol_tables/_common/assets/notes_doremi/
    - lib/tools/symbol_tables/_common/assets/notes_notevalues/
    - lib/tools/symbol_tables/_common/assets/notes_names_altoclef/
    - lib/tools/symbol_tables/_common/assets/notes_names_bassclef/
    - lib/tools/symbol_tables/_common/assets/notes_names_trebleclef/
    - lib/tools/symbol_tables/_common/assets/notes_restvalues/
    - lib/tools/symbol_tables/_common/assets/nyctography/
    - lib/tools/symbol_tables/_common/assets/oak_island_money_pit/
    - lib/tools/symbol_tables/_common/assets/oak_island_money_pit_extended/
    - lib/tools/symbol_tables/_common/assets/oak_island_money_pit_libyan/
    - lib/tools/symbol_tables/_common/assets/ogham/
    - lib/tools/symbol_tables/_common/assets/optical_fiber_fotag/
    - lib/tools/symbol_tables/_common/assets/optical_fiber_iec60304/
    - lib/tools/symbol_tables/_common/assets/optical_fiber_swisscom/
    - lib/tools/symbol_tables/_common/assets/phoenician/
    - lib/tools/symbol_tables/_common/assets/pipeline/
    - lib/tools/symbol_tables/_common/assets/pipeline_din2403/
    - lib/tools/symbol_tables/_common/assets/pixel/
    - lib/tools/symbol_tables/_common/assets/planet/
    - lib/tools/symbol_tables/_common/assets/planets/
    - lib/tools/symbol_tables/_common/assets/pokemon_unown/
    - lib/tools/symbol_tables/_common/assets/postcode_01247/
    - lib/tools/symbol_tables/_common/assets/postcode_8421/
    - lib/tools/symbol_tables/_common/assets/postnet/
    - lib/tools/symbol_tables/_common/assets/predator/
    - lib/tools/symbol_tables/_common/assets/prosyl/
    - lib/tools/symbol_tables/_common/assets/prussian_colors_artillery/
    - lib/tools/symbol_tables/_common/assets/prussian_colors_infantery/
    - lib/tools/symbol_tables/_common/assets/puzzle/
    - lib/tools/symbol_tables/_common/assets/puzzle_2/
    - lib/tools/symbol_tables/_common/assets/quadoo/
    - lib/tools/symbol_tables/_common/assets/ravkan/
    - lib/tools/symbol_tables/_common/assets/ravkan_extended/
    - lib/tools/symbol_tables/_common/assets/reality/
    - lib/tools/symbol_tables/_common/assets/red_herring/
    - lib/tools/symbol_tables/_common/assets/resistor/
    - lib/tools/symbol_tables/_common/assets/rhesus_a/
    - lib/tools/symbol_tables/_common/assets/rhesus_b/
    - lib/tools/symbol_tables/_common/assets/rhesus_c1/
    - lib/tools/symbol_tables/_common/assets/rhesus_c2/
    - lib/tools/symbol_tables/_common/assets/rm4scc/
    - lib/tools/symbol_tables/_common/assets/robots/
    - lib/tools/symbol_tables/_common/assets/romulan/
    - lib/tools/symbol_tables/_common/assets/runes/
    - lib/tools/symbol_tables/_common/assets/sanluca/
    - lib/tools/symbol_tables/_common/assets/sarati/
    - lib/tools/symbol_tables/_common/assets/semaphore/
    - lib/tools/symbol_tables/_common/assets/shadoks/
    - lib/tools/symbol_tables/_common/assets/sheikah/
    - lib/tools/symbol_tables/_common/assets/shoes/
    - lib/tools/symbol_tables/_common/assets/sign/
    - lib/tools/symbol_tables/_common/assets/siemens/
    - lib/tools/symbol_tables/_common/assets/sith/
    - lib/tools/symbol_tables/_common/assets/skullz/
    - lib/tools/symbol_tables/_common/assets/slash_and_pipe/
    - lib/tools/symbol_tables/_common/assets/solmisation/
    - lib/tools/symbol_tables/_common/assets/space_invaders/
    - lib/tools/symbol_tables/_common/assets/spintype/
    - lib/tools/symbol_tables/_common/assets/sprykski/
    - lib/tools/symbol_tables/_common/assets/stenography/
    - lib/tools/symbol_tables/_common/assets/steinheil/
    - lib/tools/symbol_tables/_common/assets/stippelcode/
    - lib/tools/symbol_tables/_common/assets/suetterlin/
    - lib/tools/symbol_tables/_common/assets/sunuz/
    - lib/tools/symbol_tables/_common/assets/surf/
    - lib/tools/symbol_tables/_common/assets/tae/
    - lib/tools/symbol_tables/_common/assets/tamil_numerals/
    - lib/tools/symbol_tables/_common/assets/telegraph_pasley/
    - lib/tools/symbol_tables/_common/assets/telegraph_popham/
    - lib/tools/symbol_tables/_common/assets/telegraph_prussia/
    - lib/tools/symbol_tables/_common/assets/templers/
    - lib/tools/symbol_tables/_common/assets/tenctonese_cursive/
    - lib/tools/symbol_tables/_common/assets/tenctonese_printed/
    - lib/tools/symbol_tables/_common/assets/tengwar_beleriand/
    - lib/tools/symbol_tables/_common/assets/tengwar_classic/
    - lib/tools/symbol_tables/_common/assets/tengwar_general/
    - lib/tools/symbol_tables/_common/assets/terzi/
    - lib/tools/symbol_tables/_common/assets/thai_numerals/
    - lib/tools/symbol_tables/_common/assets/theban/
    - lib/tools/symbol_tables/_common/assets/three_squares/
    - lib/tools/symbol_tables/_common/assets/tifinagh/
    - lib/tools/symbol_tables/_common/assets/tines/
    - lib/tools/symbol_tables/_common/assets/tomtom/
    - lib/tools/symbol_tables/_common/assets/trafficsigns_germany/
    - lib/tools/symbol_tables/_common/assets/ulog/
    - lib/tools/symbol_tables/_common/assets/unitology/
    - lib/tools/symbol_tables/_common/assets/utopian/
    - lib/tools/symbol_tables/_common/assets/visitor_1984/
    - lib/tools/symbol_tables/_common/assets/visitor_2009/
    - lib/tools/symbol_tables/_common/assets/voynich/
    - lib/tools/symbol_tables/_common/assets/vulcanian/
    - lib/tools/symbol_tables/_common/assets/wakandan/
    - lib/tools/symbol_tables/_common/assets/weather_a/
    - lib/tools/symbol_tables/_common/assets/weather_c/
    - lib/tools/symbol_tables/_common/assets/weather_cl/
    - lib/tools/symbol_tables/_common/assets/weather_cm/
    - lib/tools/symbol_tables/_common/assets/weather_ch/
    - lib/tools/symbol_tables/_common/assets/weather_n/
    - lib/tools/symbol_tables/_common/assets/weather_w/
    - lib/tools/symbol_tables/_common/assets/weather_ww/
    - lib/tools/symbol_tables/_common/assets/webdings/
    - lib/tools/symbol_tables/_common/assets/westernunion/
    - lib/tools/symbol_tables/_common/assets/windforce_beaufort/
    - lib/tools/symbol_tables/_common/assets/windforce_knots/
    - lib/tools/symbol_tables/_common/assets/window/
    - lib/tools/symbol_tables/_common/assets/wingdings/
    - lib/tools/symbol_tables/_common/assets/wingdings2/
    - lib/tools/symbol_tables/_common/assets/wingdings3/
    - lib/tools/symbol_tables/_common/assets/yan_koryani/
    - lib/tools/symbol_tables/_common/assets/yinyang/
    - lib/tools/symbol_tables/_common/assets/zamonian/
    - lib/tools/symbol_tables/_common/assets/zentradi/
    - lib/tools/symbol_tables/_common/assets/zodiac_signs/
    - lib/tools/symbol_tables/_common/assets/zodiac_signs_latin/
    - lib/tools/symbol_tables/_common/assets/zodiac_z340/
    - lib/tools/symbol_tables/_common/assets/zodiac_z408/

flutter_icons:
  image_path: "assets/logo/circle_border_1024_gold.png"
  android: true
  ios: true